config/urls.py
"""URL Configuration
"""
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.csrf import csrf_failure
from graphene_django.views import GraphQLView

from sherbet.admin import admin_site


# Standard (Django) URL patters
urlpatterns = [
    # App
    path('', include('sherbet.pages.urls', namespace='pages')),
    path('', include('sherbet.users.urls', namespace='users')),
    # Auth
    path('admin/', admin_site.urls),
    path('hijack/', include('hijack.urls', namespace='hijack')),
    # GraphQL
    path('graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "403_csrf/",
            csrf_failure,
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sherbet/pages/urls.py
from django.urls import path

from sherbet.pages import views


app_name = 'pages'

urlpatterns = [
    # App "routes"
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.AppView.as_view(), name='home'),
    path('users/', views.AppView.as_view(), name='users'),
    # SEO
    path('robots.txt', views.RobotsView.as_view(), name='robots'),
]

sherbet/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'
    ), name='logout'),
]

sherbet/assets/models.py
from django.db import models
from djmoney.models.fields import MoneyField

from sherbet.comments.models import CommentsMixin
from sherbet.families.models import FamilyMixin
from sherbet.locations.models import LocationMixin
from sherbet.models import HistoryMixin


class Asset(LocationMixin, FamilyMixin, CommentsMixin, HistoryMixin):
    cost = MoneyField(
        decimal_places=2,
        default_currency='USD',
        max_digits=14, )
    manual_url = models.URLField(blank=True)
    name = models.CharField(max_length=512)

    def __str__(self):
        return f'{self.name}'

sherbet/comments/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models

from sherbet.models import HistoryMixin
from sherbet.families.models import FamilyMixin


class Comment(FamilyMixin, HistoryMixin):
    comment = models.TextField()
    content_object = GenericForeignKey('content_type', 'object_id')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.user_created}: {self.comment[:20]}...'


class CommentsMixin(models.Model):
    comments = GenericRelation('comments.Comment')

    class Meta:
        abstract = True

sherbet/families/models.py
from django.db import models

from sherbet.models import HistoryMixin


class Family(HistoryMixin):
    name = models.CharField(max_length=512)

    class Meta:
        verbose_name_plural = 'families'

    def __str__(self):
        return f'{self.name}'


class FamilyMixin(models.Model):
    """
    Todo:
        * Might make sense to make "family" field required, non-null.
    """
    family = models.ForeignKey(
        'families.family',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='%(class)s_family',
    )

    class Meta:
        abstract = True

sherbet/locations/models.py
from django.db import models

from sherbet.families.models import FamilyMixin
from sherbet.models import HistoryMixin


class Location(FamilyMixin, HistoryMixin):
    """
    TODO: non-US localication adjustments
    """
    address_1 = models.CharField(max_length=1024)
    address_2 = models.CharField(max_length=1024, blank=True)
    city = models.CharField(max_length=512)
    name = models.CharField(max_length=512)
    state = models.CharField(max_length=2)
    zip = models.IntegerField()

    def __str__(self):
        address = ', '.join(list(filter(None, [self.address_1, self.address_2])))
        return f'{self.name} ({address}, {self.city}, {self.state} {self.zip})'


class LocationMixin(models.Model):
    location = models.ForeignKey(
        'locations.Location',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='%(class)s_location',
    )

    class Meta:
        abstract = True

sherbet/models.py
from django.db import models


class HistoryMixin(models.Model):
    """
    Todo:
        * Might make sense in its own app.
    """
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    user_created = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name='%(class)s_user_created',
    )
    user_modified = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name='%(class)s_user_modified',
    )

    class Meta:
        abstract = True

sherbet/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models # noqa

from sherbet.families.models import FamilyMixin


class User(FamilyMixin, AbstractUser):
    pass

sherbet/families/views.py
from django.shortcuts import render

# Create your views here.

sherbet/pages/views.py
from django.views.generic.base import TemplateView


class AppView(TemplateView):
    template_name = 'pages/app.html'


class IndexView(TemplateView):
    template_name = 'pages/index.html'


class RobotsView(TemplateView):
    content_type = 'text/plain'
    template_name = 'pages/robots.txt'

sherbet/pages/templates/pages/app.html
{% extends "base.html" %}

{% block title %}App{% endblock %}

{% block content %}
  <div id="sherbet-app"></div>
{% endblock %}

sherbet/pages/templates/pages/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block content %}
  <h1>Index view</h1>
  <ul>
    <li><a href="{% url 'pages:home' %}">Home</a></li>
    <li><a href="{% url 'users:login' %}">Log in</a></li>
    <li><a href="#TODO">Sign Up</a></li>
{% endblock %}

sherbet/templates/_messages.html
{% if messages %}
  {% for message in messages %}
    <div class="notification {{ message.tags }}">
      <span class="notification-text">{{ message }}</span>
    </div>
  {% endfor %}
{% endif %}

sherbet/templates/base.html
{% load hijack_tags %}
{% load static %}

{% get_static_prefix as static_prefix %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="TODO: Page Description" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %} - Sherbet</title>
    <link href="{% static '/hijack/hijack-styles.css' %}" rel="stylesheet" />
    <link href="{% static '/public.styles.css' %}" rel="stylesheet" />
    {% block html_head %}{% endblock %}
  </head>
  <body>

    {% hijack_notification %}

    <header class="global-header">
      <div class="global-header__container"></div>
    </header>

    <main role="main" class="main">
      {% include '_messages.html' %}
      {% block content %}{% endblock %}
    </main>

    <footer class="global-footer">
      <div class="global-footer__container"></div>
    </footer>

    {% if debug %}
      <style type="text/css">
        /* "body" to win specificity but allow inline overrides */
        body #djDebug #djDebugToolbarHandle { top: 80%; }
      </style>
    {% endif %}

    <script type="text/javascript" src="{{ webpack_proxy }}{{ static_prefix }}public.bundle.js"></script>
  </body>
</html>

sherbet/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'users:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

{% endblock %}